# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('awarded_on', models.DateTimeField()),
                ('category', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[(b'Nominated', b'Nominated'), (b'Won', b'Won')], max_length=50)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alternate_text', models.CharField(max_length=80)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('box_office', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, choices=[(b'Action', b'Action'), (b'Adventure', b'Adventure'), (b'Animation', b'Animation'), (b'Biography', b'Biography'), (b'Comedy', b'Comedy'), (b'Crime', b'Crime'), (b'Documentary', b'Documentary'), (b'Drama', b'Drama'), (b'Family', b'Family'), (b'Fantasy', b'Fantasy'), (b'Film-Noir', b'Film-Noir'), (b'History', b'History'), (b'Horror', b'Horror'), (b'Music', b'Music'), (b'Musical', b'Musical'), (b'Mystery', b'Mystery'), (b'Romance', b'Romance'), (b'Sci-Fi', b'Sci-Fi'), (b'Sport', b'Sport'), (b'Thriller', b'Thriller'), (b'War', b'War'), (b'Western', b'Western')], max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('released_on',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')], max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('languages_known', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('image', models.URLField()),
                ('nick_names', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Movie')),
                ('singers', models.ManyToManyField(blank=True, related_name='all_songs', to='wiki.Person')),
                ('writers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_songs', to='wiki.Person')),
            ],
        ),
        migrations.AddField(
            model_name='imageurl',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Movie'),
        ),
        migrations.AddField(
            model_name='imageurl',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Person'),
        ),
        migrations.AddField(
            model_name='award',
            name='awardee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Person'),
        ),
        migrations.AddField(
            model_name='award',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Movie'),
        ),
    ]
