# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_person_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.URLField(default='http://3.bp.blogspot.com/-Qdd729mhWis/Vbd_QDwwnJI/AAAAAAAARFI/--6Z3GTSHTM/s1600/Srimanthudu%2BFights%2B2.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.URLField(default='http://google.com/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='awardee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='wiki.Person'),
        ),
    ]
