# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20160914_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='team',
            field=models.ManyToManyField(related_name='movies', to='wiki.Person'),
        ),
    ]
