# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_movie_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
