# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_song_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageurl',
            options={'ordering': ['id']},
        ),
    ]
