# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_auto_20170108_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
