# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_auto_20170127_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music_directors',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs', to='wiki.Person'),
        ),
    ]
