# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_song_music_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
